// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kklvqihkfgbyrhukkqah.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtrbHZxaWhrZmdieXJodWtrcWFoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg1NTk4MzQsImV4cCI6MjA3NDEzNTgzNH0.e0uBQexEXerfDodc0q3LGHhtEB0Fe9pioj67yJc385o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});